servers:   # list of servers
        # sdfsdaf
  - server: # server
        server_name: 127.0.0.1
        listen: 8080
        root: ${PWD}/src/root
        client_max_body_size: 1000
        locations:
          - /:
              auto_index: true
              index:
                - index.html
                - index.htm
                - index.php
              error_page:
                - code: 40x
                  content: ${PWD}/src/root/errorsPages/503.html
                - code: 503
                  content: ${PWD}/src/root/errorsPages/503.html
              upload_directory: /var/www/html/public/uploads
              allowed_methods:
                  - POST
                  - GET
                  - DELETE
              cgi:
                  path: /Users/${USER}/.brew/bin/php-cgi
                  ext:
                    - .php
                    - .php5
                    - .php7
                    - .php-cgi
                    - .php3
                    - .php4
                    - .php5
                    - .php6
