servers:   # list of servers
        # sdfsdaf
   - server: # server
        server_name : localhost # name of the server
        listen : 8080 # listen port
        root : /var/www/html/public # root directory
        locations: # list of locations
            - /ssr: # location
                auto_index: true # auto index
   - server: # server
        server_name: 127.0.0.1
        listen: 80
        root: /var/www/html/public
        client_max_body_size: 1000
        locations:
          - / :
                error_page:
                 - code: 500
                   content: ./Networking/index.html
                 - code: 502
                   content: ./Networking/index.html
                upload_directory: /var/www/html/public/uploads
                allowed_methods:
                 - POST
                 - GET
                 - DELETE
                cgi:
                 path: ./Networking/index.html
                 ext:
                  - .php
                  - .php5
                  - .php7
                  - .php-cgi
                  - .php3
                  - .php4
                  - .php5
                  - .php6
          - /ssr:
                 index:
                   - index.html
                   - index.htm
                   - index.php