servers:   # list of servers
        # sdfsdaf
  - server: # server
        server_name: 127.0.0.1
        listen: 80
        root: ./Networking
        client_max_body_size: 1000
        locations:
          - /:
              auto_index: true
              index:
                - index.html
                - index.htm
                - index.php
              error_page:
                - code: 500
                  content: ./Networking/index.html
                - code: 502
                  content: ./Networking/index.html
              upload_directory: /var/www/html/public/uploads
              allowed_methods:
                  - POST
                  - GET
                  - DELETE
              cgi:
                  path: ./Networking/index.html
                  ext:
                    - .php
                    - .php5
                    - .php7
                    - .php-cgi
                    - .php3
                    - .php4
                    - .php5
                    - .php6
  - server: # server
      server_name: 127.0.0.2
      listen: 80
      root: ./Networking
      client_max_body_size: 1000
      locations:
        - /:
            auto_index: true
            error_page:
              - code: 500
                content: ./Networking/index.html
              - code: 502
                content: ./Networking/index.html
            upload_directory: /var/www/html/public/uploads
            allowed_methods:
                - POST
                - GET
                - DELETE
            cgi:
                path: ./Networking/index.html
                ext:
                  - .php
                  - .php5
                  - .php7
                  - .php-cgi
                  - .php3
                  - .php4
                  - .php5
                  - .php6
  - server: # server
        server_name: 127.0.0.1
        listen: 8081
        root: ./Networking
        client_max_body_size: 1000
        locations:
          - /:
               auto_index: true
              error_page:
                - code: 500
                  content: ./Networking/index.html
                - code: 502
                  content: ./Networking/index.html
              upload_directory: /var/www/html/public/uploads
              allowed_methods:
                 - POST
                 - GET
                 - DELETE
              cgi:
                 path: ./Networking/index.html
                 ext:
                  - .php
                  - .php5
                  - .php7
                  - .php-cgi
                  - .php3
                  - .php4
                  - .php5
                  - .php6
