servers:   # list of servers
        # sdfsdaf
   - server: # server
        server_name : localhost # name of the server
        listen : 80 # listen port
        root : /var/www/html/public # root directory
        locations: # list of locations
            - /ssr: # location
                auto_index: true # auto index
   - server: # server
        server_name: localhost
        listen: 80
        root: /var/www/html/public
        locations:
           - /ssr:
               index:
                - index.html
                - index.htm
                - index.php
           - / :
                error_page:
                 - code: 500
                   content: /500.html
                 - code: 502
                   content: /502.html
                upload_directory: /var/www/html/public/uploads
                allowed_methods:
                 - POST
                 - GET
                 - DELETE
                client_max_body_size: 1000
                cgi:
                 path: /bin/php
                 ext:
                  - .php
                  - .php5
                  - .php7
                  - .php-cgi
                  - .php3
                  - .php4
                  - .php5
                  - .php6
